language: ruby
rvm:
- 2.2.4
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec rubocop
services:
- postgresql
deploy:
  provider: heroku
  run:
  - rake db:migrate
  api_key:
    secure: bCNMm7NpK/K2zmn8NdS617XrFudjh+3MzWRhh2B54LtgUGhb8KgvVyzdvYzlUYK8T9ozniG4juE+e1U/fMy9MtClXthCrcWzOd+zzZjS4gYwKU2p2pAplMLWwfzwOVL8fwVc1vm5rYLEOnx48QKhIduYKMVf5uyoSDN/vZChShY6y0bbfKaiuI1ynHsrQxGO9LC4fRQ4Jv7VoZrj8MdR5/zo1lA0yDNQwo9A2OakKKGxcefv15Fiz2ZiDRuqA/zS8639OuWyzYp94oPYoHI71ETEppexYonSnKOutPU6qlU7YIoptO+vM++uqpJywzEgTp2Cee091gaBiC/kEA+CKyyGN2aWaUpvzYe/0qqY2RkUO+cDXe1oYCvD+1AkwYoNKGsdUcaYNK4QWnRw10nMkVgJ7v6mWGskreQyfRH+fAXKwG+fqqxESIyPflO2yRQnSROMuf10fbnoP+In6ymDu9RYafBZfcnEaHIVZUUli6uf5DmADFEpLJNsGH/X9wxBawO3GbH9McHWaABE5UGyE5AsYrkQ/onZK34BPPUoIe/I3l123cbs4EKDlpoSIghrfdRVV/ZZhqIL3LSu3oE1W1giHe42YTiEbPq40AGLlUH5a8LpYZYRpuUcEBujACcZaje0DYW7QoAcZ/K5ObFc1omA9N0S/zrHsbxXt/9vLWA=
  app:
    master: team-up-today
  on:
    repo: tohyung85/team-up-today
