language: ruby
rvm:
- 2.2.4
before_install: gem update --remote bundler
install:
- bundle install --retry=3
script:
- bundle exec rake db:test:prepare
- bundle exec rspec
- bundle exec rubocop
services:
- postgresql
deploy:
  provider: heroku
  run:
  - rake db:migrate
  api_key:
    secure: "KRk+UWMKRo/8DKsTfWk53xvwMCBtEK21YY1RAsfeFL0bACf7kbzp+aK1kKiXCgjpklBfLycPlYklrX7Pe/87WFS95akROyHBSNKNbFpNJXbgfXbx3cZx/ho5wF8nV9tAcCkEpGIlHr7R3UiuJje3GtBMV1Qh+ux40Cz/cDn4cXfgg+hMZ0nnZWmJz6Zy6HRRBcAcus5a5GfQrlQvUrBg6gHdiqIeCvRU3O+fxF8vrf5GMr6IaQhA10zUQYjrjD4FYcJC4iiczjuFLfNIEU7VO26KeL4dvdZBHNqUs5uWTFYein8EL9OunY0MDAF22fx58JFt+QHnJHBRxw4eaCRToe1vzAZ2u8oO/UKNBnCQTKzluvt7vCf8rs19ENj5i3G1nGEJ1z9OY2hWF0LUcygke048Kf+TWtilbOpMRXhJ8V+QOd+6UARu05Z81o6jNryGg21/mpxyqR4XjWcva+UA32oR+Z0JhHfoyi2NlFxfVYnGYiHputu5GIRjRv/RYQUClNAY1kXkLgb7EW83BQW9yiBPB9hnAkul4CjaHyEeOVwhItbu3LNX4yaUQSUIi78X2M5RdU5m3OItqre1keoHft6E2L++M2MAcQeHsrhiB3stY7slyZRpMBuHF89H9rWkukmGP/G5/J5kkcHvvucWDc0uc+QqlicvAZi7shpHAic="
  app:
    master: team-up-today
  on:
    repo: tohyung85/team-up-today
